/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accounting.software;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.AbstractListModel;
import javax.swing.ListModel;

/**
 *
 * @author emre
 */
public class FinanceFrame extends javax.swing.JPanel {
    
    //lists   
    private static Vector<String> giderler = new Vector<String>();
    private static Vector<String> gelirler = new Vector<String>();
    
    //Dialogs
    AddFinanceDialog addDialog = new AddFinanceDialog(MainFrame.mainFrame, true);
    EditFinanceDialog editDialog  = new EditFinanceDialog(MainFrame.mainFrame, true);
    DeleteFinanceDialog deleteDialog = new DeleteFinanceDialog(MainFrame.mainFrame, true);
    
    /**
     * Creates new form FinanceFrame
     */
    public FinanceFrame() {
        initComponents();
        UpdateMe();
    }
    static int temp = 10;
    
    public static void UpdateMe(){
        outcomePanel.removeAll();
        incomePanel.removeAll();
        gelirler.clear();
        giderler.clear();
        
        int count_in = 0 , count_out = 0;
        int freeOutcomeY = 0;
        int freeIncomeY = 0;
        for(int i = 0 ; i < AccountingSystem.getInstance().getPersonnelSize(); ++i )
        {
            giderler.add(AccountingSystem.getInstance().getPerson(i).getName());
            ++count_out;
            outcomePanel.add(new gider(AccountingSystem.getInstance().getPerson(i) , freeOutcomeY));
            freeOutcomeY += 50;
        }
        
        for(int i = 0 ; i < AccountingSystem.getInstance().getFuelSize(); ++i )
        {
            giderler.add(AccountingSystem.getInstance().getFuel(i).getDescription());
            gelirler.add(AccountingSystem.getInstance().getFuel(i).getDescription());
            ++count_in;
            ++count_out;
            outcomePanel.add(new gider(AccountingSystem.getInstance().getFuel(i), freeOutcomeY));
            freeOutcomeY += 50;
            incomePanel.add(new gelir(AccountingSystem.getInstance().getFuel(i), freeIncomeY));
            freeIncomeY += 50;
           
        }
       
        for(int i = 0 ; i < AccountingSystem.getInstance().getSalesListSize(); ++i )
        {
            gelirler.add(AccountingSystem.getInstance().getSale(i).getDescription());
            ++count_in;
            incomePanel.add(new gelir(AccountingSystem.getInstance().getSale(i),freeIncomeY));
            freeIncomeY += 50;
        }
        
        if(count_in*50 >= 450)
            incomePanel.setPreferredSize(new Dimension(530, freeIncomeY + 50));
        if(count_out*50 >= 450)
            outcomePanel.setPreferredSize(new Dimension(530, freeOutcomeY + 50));

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddIncomeBut = new javax.swing.JButton();
        EditIncomeBut = new javax.swing.JButton();
        DeleteIncomeBut = new javax.swing.JButton();
        AddOutcomeBut = new javax.swing.JButton();
        EditOutcomeBut = new javax.swing.JButton();
        DeleteOutcomeBut = new javax.swing.JButton();
        leftPane = new javax.swing.JScrollPane();
        incomePanel = new javax.swing.JPanel();
        rightPane = new javax.swing.JScrollPane();
        outcomePanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1149, 580));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("INCOMES");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("OUTCOMES");

        AddIncomeBut.setText("Add");
        AddIncomeBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIncomeButActionPerformed(evt);
            }
        });

        EditIncomeBut.setText("Edit");
        EditIncomeBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditIncomeButActionPerformed(evt);
            }
        });

        DeleteIncomeBut.setText("Delete");

        AddOutcomeBut.setText("Add");

        EditOutcomeBut.setText("Edit");

        DeleteOutcomeBut.setText("Delete");

        leftPane.setPreferredSize(new java.awt.Dimension(548, 430));

        incomePanel.setPreferredSize(new java.awt.Dimension(530, 450));

        javax.swing.GroupLayout incomePanelLayout = new javax.swing.GroupLayout(incomePanel);
        incomePanel.setLayout(incomePanelLayout);
        incomePanelLayout.setHorizontalGroup(
            incomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );
        incomePanelLayout.setVerticalGroup(
            incomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        leftPane.setViewportView(incomePanel);

        outcomePanel.setPreferredSize(new java.awt.Dimension(530, 450));

        javax.swing.GroupLayout outcomePanelLayout = new javax.swing.GroupLayout(outcomePanel);
        outcomePanel.setLayout(outcomePanelLayout);
        outcomePanelLayout.setHorizontalGroup(
            outcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        outcomePanelLayout.setVerticalGroup(
            outcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        rightPane.setViewportView(outcomePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(269, 269, 269))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rightPane, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(AddIncomeBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditIncomeBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteIncomeBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddOutcomeBut)
                .addGap(18, 18, 18)
                .addComponent(EditOutcomeBut)
                .addGap(18, 18, 18)
                .addComponent(DeleteOutcomeBut)
                .addGap(194, 194, 194))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(leftPane, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddOutcomeBut)
                        .addComponent(EditOutcomeBut)
                        .addComponent(DeleteOutcomeBut))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddIncomeBut)
                        .addComponent(EditIncomeBut)
                        .addComponent(DeleteIncomeBut)))
                .addGap(0, 31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddIncomeButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIncomeButActionPerformed
        addDialog.setVisible(true);
        
        if(addDialog.getReturnStatus() == AddFinanceDialog.RET_OK){
            String[] s = new String[3];
            s = addDialog.GetValues();
            
            SalesClass sale = new SalesClass(s[1],temp,Integer.parseInt(s[2]));
            AccountingSystem.getInstance().addSale(sale);
            UpdateMe();
            temp++;
        }
    }//GEN-LAST:event_AddIncomeButActionPerformed

    
    private void EditIncomeButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditIncomeButActionPerformed
        editDialog.setVisible(true);
        editDialog.list.setListData(gelirler);
        if(editDialog.getReturnStatus() == EditFinanceDialog.RET_OK){
            
        }
    }//GEN-LAST:event_EditIncomeButActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        
    }//GEN-LAST:event_formFocusGained
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddIncomeBut;
    private javax.swing.JButton AddOutcomeBut;
    private javax.swing.JButton DeleteIncomeBut;
    private javax.swing.JButton DeleteOutcomeBut;
    private javax.swing.JButton EditIncomeBut;
    private javax.swing.JButton EditOutcomeBut;
    private static javax.swing.JPanel incomePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane leftPane;
    private static javax.swing.JPanel outcomePanel;
    private javax.swing.JScrollPane rightPane;
    // End of variables declaration//GEN-END:variables
}
