/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accounting.software;

import java.awt.Dialog;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataEvent;

/**
 *
 * @author emre
 */
public class personnelFrame extends javax.swing.JPanel {

    //Personnel List
    List<Personnel> personnels;
    
    /**
     * Creates new form personnelFrame
     */
    public personnelFrame() {
        fillPersonnelComboBox();
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectPersonnel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idTextBox = new javax.swing.JTextField();
        nameTextBox = new javax.swing.JTextField();
        surnameTextBox = new javax.swing.JTextField();
        phoneTextBox = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        sskPrimTextBox = new javax.swing.JTextField();
        salaryTextBox = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1149, 580));

        selectPersonnel.setName(""); // NOI18N
        selectPersonnel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectPersonnelİtemStateChanged(evt);
            }
        });
        selectPersonnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPersonnelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel1.setText("ID number         :");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel7.setText("Name                :");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel8.setText("Surname           :");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel9.setText("Phone Number  :");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel10.setText("Address             :");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel11.setText("SSk Primi         :");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel12.setText("Salary              :");

        idTextBox.setEditable(false);
        idTextBox.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        idTextBox.setText("Idnumb");
        idTextBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        idTextBox.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        nameTextBox.setEditable(false);
        nameTextBox.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        nameTextBox.setText("Name");
        nameTextBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameTextBox.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        nameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextBoxActionPerformed(evt);
            }
        });

        surnameTextBox.setEditable(false);
        surnameTextBox.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        surnameTextBox.setText("Surname");
        surnameTextBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        surnameTextBox.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        phoneTextBox.setEditable(false);
        phoneTextBox.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        phoneTextBox.setText("Phone Number");
        phoneTextBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        phoneTextBox.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        addressField.setEditable(false);
        addressField.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        addressField.setText("Address");
        addressField.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        sskPrimTextBox.setEditable(false);
        sskPrimTextBox.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        sskPrimTextBox.setText("SSK prim");
        sskPrimTextBox.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        salaryTextBox.setEditable(false);
        salaryTextBox.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        salaryTextBox.setText("Salary");
        salaryTextBox.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Delete");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selectPersonnel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(surnameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(phoneTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(addressField, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(idTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(sskPrimTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(salaryTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap(606, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(selectPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(surnameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(phoneTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sskPrimTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(salaryTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Finds a given name in list
     * @param name
     * @return returns index of founded otherwise -1
     */
    private int findIndexinList(String name){
        if(personnels == null)
            return -1;
        if(personnels.isEmpty())
            return -1;
        for(int i = 0 ; i < personnels.size(); ++i){
            if(personnels.get(i).getName().equals(name)){
                return i;
            }
        }
        return -1;
    }
    private void fillPersonnelComboBox(){
        personnels = AccountingSystem.getInstance().personnelList;
        for (Personnel elem : personnels){
            selectPersonnel.addItem(elem.getName());            
        }
    }
    
    private void selectPersonnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPersonnelActionPerformed
        // TODO add your handling code here:
        String name = (String)selectPersonnel.getSelectedItem();
        int index = findIndexinList(name);
        if(index == -1)
            return;
        Personnel pers= personnels.get(index);
        idTextBox.setText(String.valueOf(pers.getId()));
        nameTextBox.setText(pers.getName());
        surnameTextBox.setText(pers.getLastName());
        phoneTextBox.setText(pers.getPhoneNumber());
        addressField.setText(pers.getAddress());
        sskPrimTextBox.setText(String.valueOf(pers.getSskBonus()));
        salaryTextBox.setText(Double.toString(pers.getSalary()));
    }//GEN-LAST:event_selectPersonnelActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if(editButton.getText().equals( "Edit")){
            editButton.setText("Done");
            idTextBox.setEditable(true);
            nameTextBox.setEditable(true);
            surnameTextBox.setEditable(true);
            phoneTextBox.setEditable(true);
            addressField.setEditable(true);
            sskPrimTextBox.setEditable(true);
            salaryTextBox.setEditable(true);
        }
        else{
            editButton.setText("Edit");
            idTextBox.setEditable(false);
            nameTextBox.setEditable(false);
            surnameTextBox.setEditable(false);
            phoneTextBox.setEditable(false);
            addressField.setEditable(false);
            sskPrimTextBox.setEditable(false);
            salaryTextBox.setEditable(false);
            String name = (String)selectPersonnel.getSelectedItem();
            int index = findIndexinList(name);
            Personnel pers;
            if(index != -1)
                pers= personnels.get(index);
            else 
                return;
            try{
                pers.setId(Integer.parseInt(idTextBox.getText()));
                pers.setAddress(addressField.getText());
                pers.setLastName(surnameTextBox.getText());
                pers.setName(nameTextBox.getText());
                pers.setPhoneNumber(phoneTextBox.getText());
                pers.setSalary(Double.parseDouble(salaryTextBox.getText()));
                pers.setSskBonus(Double.parseDouble(salaryTextBox.getText()));
            }
            catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(this, ex.getMessage(),"Error !!",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void nameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextBoxActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Personnel pers = new Personnel();
        try{
            pers.setId(Integer.parseInt(idTextBox.getText()));
            pers.setAddress(addressField.getText());
            pers.setLastName(surnameTextBox.getText());
            pers.setName(nameTextBox.getText());
            pers.setPhoneNumber(phoneTextBox.getText());
            pers.setSalary(Integer.parseInt(salaryTextBox.getText()));
            pers.setSskBonus(Double.parseDouble(salaryTextBox.getText()));
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error !!",JOptionPane.ERROR_MESSAGE);
        }
        int size1 = AccountingSystem.getInstance().personnelList.size();
        AccountingSystem.getInstance().addPerson(pers);
        if(size1 != AccountingSystem.getInstance().personnelList.size())
            selectPersonnel.addItem(pers.getName());
    }//GEN-LAST:event_addButtonActionPerformed

    private void selectPersonnelİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectPersonnelİtemStateChanged
        
    }//GEN-LAST:event_selectPersonnelİtemStateChanged
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addressField;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField idTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTextBox;
    private javax.swing.JTextField phoneTextBox;
    private javax.swing.JButton removeButton;
    private javax.swing.JTextField salaryTextBox;
    private javax.swing.JComboBox<String> selectPersonnel;
    private javax.swing.JTextField sskPrimTextBox;
    private javax.swing.JTextField surnameTextBox;
    // End of variables declaration//GEN-END:variables
}
